// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/asab/AdminDashboard.tsx": () => import("../components/mockups/asab/AdminDashboard.tsx"),
  "./components/mockups/asab/BranchManagerDashboard.tsx": () => import("../components/mockups/asab/BranchManagerDashboard.tsx"),
  "./components/mockups/asab/CashCustodyModule.tsx": () => import("../components/mockups/asab/CashCustodyModule.tsx"),
  "./components/mockups/asab/ERPExportScreen.tsx": () => import("../components/mockups/asab/ERPExportScreen.tsx"),
  "./components/mockups/asab/HeadAccountantDashboard.tsx": () => import("../components/mockups/asab/HeadAccountantDashboard.tsx"),
  "./components/mockups/asab/InventoryModule.tsx": () => import("../components/mockups/asab/InventoryModule.tsx"),
  "./components/mockups/asab/MainDashboard.tsx": () => import("../components/mockups/asab/MainDashboard.tsx"),
  "./components/mockups/asab/ProcurementDashboard.tsx": () => import("../components/mockups/asab/ProcurementDashboard.tsx"),
  "./components/mockups/asab/ReportsManager.tsx": () => import("../components/mockups/asab/ReportsManager.tsx"),
  "./components/mockups/asab/SalesModule.tsx": () => import("../components/mockups/asab/SalesModule.tsx"),
  "./components/mockups/asab/SupplierDashboard.tsx": () => import("../components/mockups/asab/SupplierDashboard.tsx")
};
